services:
  copilot-minimal:
    build: .
    container_name: copilot-minimal-cli
    volumes:
      - ./logs:/app/logs
      - ./input:/app/input
      - ./prompt:/app/prompt
    restart: unless-stopped

    command: ["tail", "-f", "/dev/null"]
