name: Run agent mode

on:
  workflow_dispatch:

jobs:
  run-console-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Delete all folders in input and output
      run: |
        for dir in input output; do
          if [ -d "$dir" ]; then
            find "$dir" -mindepth 1 -type d -exec rm -rf {} +
          fi
        done

    - name: Clone repositories from list
      run: |
        if [ -f "input/repos.txt" ]; then
          while IFS= read -r repo || [ -n "$repo" ]; do
            if [ -n "$repo" ]; then
              echo "Cloning $repo (main branch, shallow)"
              # Try to clone main, fallback to master if main does not exist
              git clone --branch main --depth 1 "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$repo.git" "input/$(basename $repo)" \
                || git clone --branch master --depth 1 "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$repo.git" "input/$(basename $repo)"
            fi
          done < input/repos.txt
        else
          echo "input/repos.txt file not found, skipping repository cloning"
        fi

    - name: Show input folder file tree [DEBUG]
      run: |
        echo "File tree of input folder after cloning:"
        ls -R input

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'pnpm'

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
        run_install: false

    - name: Install dependencies
      run: pnpm install

    - name: Mask Copilot token
      run: echo "::add-mask::${{ secrets.PAT }}"

    - name: Run ask[TEST]
      run: tsx src/main.ts analyze --token ${{ secrets.PAT }} 

    - name: Echo all files contents in output folder
      run: |
        if [ -d "output" ]; then
          find output -type f -exec sh -c 'echo "----- {} -----"; cat "{}"; echo' \;
        else
          echo "output folder not found"
        fi

  